/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoSaidItRouteImport } from './routes/who-said-it'
import { Route as WheelRouteImport } from './routes/wheel'
import { Route as VoiceMeterRouteImport } from './routes/voice-meter'
import { Route as VocabRouteImport } from './routes/vocab'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as UnhingedRouteImport } from './routes/unhinged'
import { Route as StormRouteImport } from './routes/storm'
import { Route as StartersRouteImport } from './routes/starters'
import { Route as SpotlightRouteImport } from './routes/spotlight'
import { Route as SleepIndexRouteImport } from './routes/sleep-index'
import { Route as ShipsRouteImport } from './routes/ships'
import { Route as SecretFinalRouteImport } from './routes/secret-final'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RivalryRouteImport } from './routes/rivalry'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as QuietDaysRouteImport } from './routes/quiet-days'
import { Route as PatchNotesRouteImport } from './routes/patch-notes'
import { Route as PairsRouteImport } from './routes/pairs'
import { Route as NightOwlsRouteImport } from './routes/night-owls'
import { Route as NameSagaRouteImport } from './routes/name-saga'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as MonthlyRouteImport } from './routes/monthly'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoreRouteImport } from './routes/lore'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HotWordsRouteImport } from './routes/hot-words'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as EmmaHospitalRouteImport } from './routes/emma-hospital'
import { Route as EasterEggsRouteImport } from './routes/easter-eggs'
import { Route as DramaRouteImport } from './routes/drama'
import { Route as CurseWallRouteImport } from './routes/curse-wall'
import { Route as ConfessionRouteImport } from './routes/confession'
import { Route as BeefRouteImport } from './routes/beef'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'

const WhoSaidItRoute = WhoSaidItRouteImport.update({
  id: '/who-said-it',
  path: '/who-said-it',
  getParentRoute: () => rootRouteImport,
} as any)
const WheelRoute = WheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceMeterRoute = VoiceMeterRouteImport.update({
  id: '/voice-meter',
  path: '/voice-meter',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabRoute = VocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const UnhingedRoute = UnhingedRouteImport.update({
  id: '/unhinged',
  path: '/unhinged',
  getParentRoute: () => rootRouteImport,
} as any)
const StormRoute = StormRouteImport.update({
  id: '/storm',
  path: '/storm',
  getParentRoute: () => rootRouteImport,
} as any)
const StartersRoute = StartersRouteImport.update({
  id: '/starters',
  path: '/starters',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotlightRoute = SpotlightRouteImport.update({
  id: '/spotlight',
  path: '/spotlight',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepIndexRoute = SleepIndexRouteImport.update({
  id: '/sleep-index',
  path: '/sleep-index',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipsRoute = ShipsRouteImport.update({
  id: '/ships',
  path: '/ships',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretFinalRoute = SecretFinalRouteImport.update({
  id: '/secret-final',
  path: '/secret-final',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RivalryRoute = RivalryRouteImport.update({
  id: '/rivalry',
  path: '/rivalry',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuietDaysRoute = QuietDaysRouteImport.update({
  id: '/quiet-days',
  path: '/quiet-days',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchNotesRoute = PatchNotesRouteImport.update({
  id: '/patch-notes',
  path: '/patch-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PairsRoute = PairsRouteImport.update({
  id: '/pairs',
  path: '/pairs',
  getParentRoute: () => rootRouteImport,
} as any)
const NightOwlsRoute = NightOwlsRouteImport.update({
  id: '/night-owls',
  path: '/night-owls',
  getParentRoute: () => rootRouteImport,
} as any)
const NameSagaRoute = NameSagaRouteImport.update({
  id: '/name-saga',
  path: '/name-saga',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyRoute = MonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoreRoute = LoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HotWordsRoute = HotWordsRouteImport.update({
  id: '/hot-words',
  path: '/hot-words',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const EmmaHospitalRoute = EmmaHospitalRouteImport.update({
  id: '/emma-hospital',
  path: '/emma-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const EasterEggsRoute = EasterEggsRouteImport.update({
  id: '/easter-eggs',
  path: '/easter-eggs',
  getParentRoute: () => rootRouteImport,
} as any)
const DramaRoute = DramaRouteImport.update({
  id: '/drama',
  path: '/drama',
  getParentRoute: () => rootRouteImport,
} as any)
const CurseWallRoute = CurseWallRouteImport.update({
  id: '/curse-wall',
  path: '/curse-wall',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfessionRoute = ConfessionRouteImport.update({
  id: '/confession',
  path: '/confession',
  getParentRoute: () => rootRouteImport,
} as any)
const BeefRoute = BeefRouteImport.update({
  id: '/beef',
  path: '/beef',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/awards': typeof AwardsRoute
  '/beef': typeof BeefRoute
  '/confession': typeof ConfessionRoute
  '/curse-wall': typeof CurseWallRoute
  '/drama': typeof DramaRoute
  '/easter-eggs': typeof EasterEggsRoute
  '/emma-hospital': typeof EmmaHospitalRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/heatmap': typeof HeatmapRoute
  '/hot-words': typeof HotWordsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lore': typeof LoreRoute
  '/members': typeof MembersRoute
  '/monthly': typeof MonthlyRoute
  '/mood': typeof MoodRoute
  '/name-saga': typeof NameSagaRoute
  '/night-owls': typeof NightOwlsRoute
  '/pairs': typeof PairsRoute
  '/patch-notes': typeof PatchNotesRoute
  '/quiet-days': typeof QuietDaysRoute
  '/quotes': typeof QuotesRoute
  '/replay': typeof ReplayRoute
  '/rivalry': typeof RivalryRoute
  '/search': typeof SearchRoute
  '/secret-final': typeof SecretFinalRoute
  '/ships': typeof ShipsRoute
  '/sleep-index': typeof SleepIndexRoute
  '/spotlight': typeof SpotlightRoute
  '/starters': typeof StartersRoute
  '/storm': typeof StormRoute
  '/unhinged': typeof UnhingedRoute
  '/vault': typeof VaultRoute
  '/vocab': typeof VocabRoute
  '/voice-meter': typeof VoiceMeterRoute
  '/wheel': typeof WheelRoute
  '/who-said-it': typeof WhoSaidItRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/awards': typeof AwardsRoute
  '/beef': typeof BeefRoute
  '/confession': typeof ConfessionRoute
  '/curse-wall': typeof CurseWallRoute
  '/drama': typeof DramaRoute
  '/easter-eggs': typeof EasterEggsRoute
  '/emma-hospital': typeof EmmaHospitalRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/heatmap': typeof HeatmapRoute
  '/hot-words': typeof HotWordsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lore': typeof LoreRoute
  '/members': typeof MembersRoute
  '/monthly': typeof MonthlyRoute
  '/mood': typeof MoodRoute
  '/name-saga': typeof NameSagaRoute
  '/night-owls': typeof NightOwlsRoute
  '/pairs': typeof PairsRoute
  '/patch-notes': typeof PatchNotesRoute
  '/quiet-days': typeof QuietDaysRoute
  '/quotes': typeof QuotesRoute
  '/replay': typeof ReplayRoute
  '/rivalry': typeof RivalryRoute
  '/search': typeof SearchRoute
  '/secret-final': typeof SecretFinalRoute
  '/ships': typeof ShipsRoute
  '/sleep-index': typeof SleepIndexRoute
  '/spotlight': typeof SpotlightRoute
  '/starters': typeof StartersRoute
  '/storm': typeof StormRoute
  '/unhinged': typeof UnhingedRoute
  '/vault': typeof VaultRoute
  '/vocab': typeof VocabRoute
  '/voice-meter': typeof VoiceMeterRoute
  '/wheel': typeof WheelRoute
  '/who-said-it': typeof WhoSaidItRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/awards': typeof AwardsRoute
  '/beef': typeof BeefRoute
  '/confession': typeof ConfessionRoute
  '/curse-wall': typeof CurseWallRoute
  '/drama': typeof DramaRoute
  '/easter-eggs': typeof EasterEggsRoute
  '/emma-hospital': typeof EmmaHospitalRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/heatmap': typeof HeatmapRoute
  '/hot-words': typeof HotWordsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lore': typeof LoreRoute
  '/members': typeof MembersRoute
  '/monthly': typeof MonthlyRoute
  '/mood': typeof MoodRoute
  '/name-saga': typeof NameSagaRoute
  '/night-owls': typeof NightOwlsRoute
  '/pairs': typeof PairsRoute
  '/patch-notes': typeof PatchNotesRoute
  '/quiet-days': typeof QuietDaysRoute
  '/quotes': typeof QuotesRoute
  '/replay': typeof ReplayRoute
  '/rivalry': typeof RivalryRoute
  '/search': typeof SearchRoute
  '/secret-final': typeof SecretFinalRoute
  '/ships': typeof ShipsRoute
  '/sleep-index': typeof SleepIndexRoute
  '/spotlight': typeof SpotlightRoute
  '/starters': typeof StartersRoute
  '/storm': typeof StormRoute
  '/unhinged': typeof UnhingedRoute
  '/vault': typeof VaultRoute
  '/vocab': typeof VocabRoute
  '/voice-meter': typeof VoiceMeterRoute
  '/wheel': typeof WheelRoute
  '/who-said-it': typeof WhoSaidItRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/awards'
    | '/beef'
    | '/confession'
    | '/curse-wall'
    | '/drama'
    | '/easter-eggs'
    | '/emma-hospital'
    | '/hall-of-fame'
    | '/heatmap'
    | '/hot-words'
    | '/leaderboard'
    | '/lore'
    | '/members'
    | '/monthly'
    | '/mood'
    | '/name-saga'
    | '/night-owls'
    | '/pairs'
    | '/patch-notes'
    | '/quiet-days'
    | '/quotes'
    | '/replay'
    | '/rivalry'
    | '/search'
    | '/secret-final'
    | '/ships'
    | '/sleep-index'
    | '/spotlight'
    | '/starters'
    | '/storm'
    | '/unhinged'
    | '/vault'
    | '/vocab'
    | '/voice-meter'
    | '/wheel'
    | '/who-said-it'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/awards'
    | '/beef'
    | '/confession'
    | '/curse-wall'
    | '/drama'
    | '/easter-eggs'
    | '/emma-hospital'
    | '/hall-of-fame'
    | '/heatmap'
    | '/hot-words'
    | '/leaderboard'
    | '/lore'
    | '/members'
    | '/monthly'
    | '/mood'
    | '/name-saga'
    | '/night-owls'
    | '/pairs'
    | '/patch-notes'
    | '/quiet-days'
    | '/quotes'
    | '/replay'
    | '/rivalry'
    | '/search'
    | '/secret-final'
    | '/ships'
    | '/sleep-index'
    | '/spotlight'
    | '/starters'
    | '/storm'
    | '/unhinged'
    | '/vault'
    | '/vocab'
    | '/voice-meter'
    | '/wheel'
    | '/who-said-it'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/awards'
    | '/beef'
    | '/confession'
    | '/curse-wall'
    | '/drama'
    | '/easter-eggs'
    | '/emma-hospital'
    | '/hall-of-fame'
    | '/heatmap'
    | '/hot-words'
    | '/leaderboard'
    | '/lore'
    | '/members'
    | '/monthly'
    | '/mood'
    | '/name-saga'
    | '/night-owls'
    | '/pairs'
    | '/patch-notes'
    | '/quiet-days'
    | '/quotes'
    | '/replay'
    | '/rivalry'
    | '/search'
    | '/secret-final'
    | '/ships'
    | '/sleep-index'
    | '/spotlight'
    | '/starters'
    | '/storm'
    | '/unhinged'
    | '/vault'
    | '/vocab'
    | '/voice-meter'
    | '/wheel'
    | '/who-said-it'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AwardsRoute: typeof AwardsRoute
  BeefRoute: typeof BeefRoute
  ConfessionRoute: typeof ConfessionRoute
  CurseWallRoute: typeof CurseWallRoute
  DramaRoute: typeof DramaRoute
  EasterEggsRoute: typeof EasterEggsRoute
  EmmaHospitalRoute: typeof EmmaHospitalRoute
  HallOfFameRoute: typeof HallOfFameRoute
  HeatmapRoute: typeof HeatmapRoute
  HotWordsRoute: typeof HotWordsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoreRoute: typeof LoreRoute
  MembersRoute: typeof MembersRoute
  MonthlyRoute: typeof MonthlyRoute
  MoodRoute: typeof MoodRoute
  NameSagaRoute: typeof NameSagaRoute
  NightOwlsRoute: typeof NightOwlsRoute
  PairsRoute: typeof PairsRoute
  PatchNotesRoute: typeof PatchNotesRoute
  QuietDaysRoute: typeof QuietDaysRoute
  QuotesRoute: typeof QuotesRoute
  ReplayRoute: typeof ReplayRoute
  RivalryRoute: typeof RivalryRoute
  SearchRoute: typeof SearchRoute
  SecretFinalRoute: typeof SecretFinalRoute
  ShipsRoute: typeof ShipsRoute
  SleepIndexRoute: typeof SleepIndexRoute
  SpotlightRoute: typeof SpotlightRoute
  StartersRoute: typeof StartersRoute
  StormRoute: typeof StormRoute
  UnhingedRoute: typeof UnhingedRoute
  VaultRoute: typeof VaultRoute
  VocabRoute: typeof VocabRoute
  VoiceMeterRoute: typeof VoiceMeterRoute
  WheelRoute: typeof WheelRoute
  WhoSaidItRoute: typeof WhoSaidItRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who-said-it': {
      id: '/who-said-it'
      path: '/who-said-it'
      fullPath: '/who-said-it'
      preLoaderRoute: typeof WhoSaidItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wheel': {
      id: '/wheel'
      path: '/wheel'
      fullPath: '/wheel'
      preLoaderRoute: typeof WheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-meter': {
      id: '/voice-meter'
      path: '/voice-meter'
      fullPath: '/voice-meter'
      preLoaderRoute: typeof VoiceMeterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab': {
      id: '/vocab'
      path: '/vocab'
      fullPath: '/vocab'
      preLoaderRoute: typeof VocabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unhinged': {
      id: '/unhinged'
      path: '/unhinged'
      fullPath: '/unhinged'
      preLoaderRoute: typeof UnhingedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storm': {
      id: '/storm'
      path: '/storm'
      fullPath: '/storm'
      preLoaderRoute: typeof StormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starters': {
      id: '/starters'
      path: '/starters'
      fullPath: '/starters'
      preLoaderRoute: typeof StartersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotlight': {
      id: '/spotlight'
      path: '/spotlight'
      fullPath: '/spotlight'
      preLoaderRoute: typeof SpotlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep-index': {
      id: '/sleep-index'
      path: '/sleep-index'
      fullPath: '/sleep-index'
      preLoaderRoute: typeof SleepIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ships': {
      id: '/ships'
      path: '/ships'
      fullPath: '/ships'
      preLoaderRoute: typeof ShipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret-final': {
      id: '/secret-final'
      path: '/secret-final'
      fullPath: '/secret-final'
      preLoaderRoute: typeof SecretFinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rivalry': {
      id: '/rivalry'
      path: '/rivalry'
      fullPath: '/rivalry'
      preLoaderRoute: typeof RivalryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiet-days': {
      id: '/quiet-days'
      path: '/quiet-days'
      fullPath: '/quiet-days'
      preLoaderRoute: typeof QuietDaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patch-notes': {
      id: '/patch-notes'
      path: '/patch-notes'
      fullPath: '/patch-notes'
      preLoaderRoute: typeof PatchNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairs': {
      id: '/pairs'
      path: '/pairs'
      fullPath: '/pairs'
      preLoaderRoute: typeof PairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night-owls': {
      id: '/night-owls'
      path: '/night-owls'
      fullPath: '/night-owls'
      preLoaderRoute: typeof NightOwlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name-saga': {
      id: '/name-saga'
      path: '/name-saga'
      fullPath: '/name-saga'
      preLoaderRoute: typeof NameSagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly': {
      id: '/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof MonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lore': {
      id: '/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof LoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-words': {
      id: '/hot-words'
      path: '/hot-words'
      fullPath: '/hot-words'
      preLoaderRoute: typeof HotWordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emma-hospital': {
      id: '/emma-hospital'
      path: '/emma-hospital'
      fullPath: '/emma-hospital'
      preLoaderRoute: typeof EmmaHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/easter-eggs': {
      id: '/easter-eggs'
      path: '/easter-eggs'
      fullPath: '/easter-eggs'
      preLoaderRoute: typeof EasterEggsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drama': {
      id: '/drama'
      path: '/drama'
      fullPath: '/drama'
      preLoaderRoute: typeof DramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curse-wall': {
      id: '/curse-wall'
      path: '/curse-wall'
      fullPath: '/curse-wall'
      preLoaderRoute: typeof CurseWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confession': {
      id: '/confession'
      path: '/confession'
      fullPath: '/confession'
      preLoaderRoute: typeof ConfessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beef': {
      id: '/beef'
      path: '/beef'
      fullPath: '/beef'
      preLoaderRoute: typeof BeefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AwardsRoute: AwardsRoute,
  BeefRoute: BeefRoute,
  ConfessionRoute: ConfessionRoute,
  CurseWallRoute: CurseWallRoute,
  DramaRoute: DramaRoute,
  EasterEggsRoute: EasterEggsRoute,
  EmmaHospitalRoute: EmmaHospitalRoute,
  HallOfFameRoute: HallOfFameRoute,
  HeatmapRoute: HeatmapRoute,
  HotWordsRoute: HotWordsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoreRoute: LoreRoute,
  MembersRoute: MembersRoute,
  MonthlyRoute: MonthlyRoute,
  MoodRoute: MoodRoute,
  NameSagaRoute: NameSagaRoute,
  NightOwlsRoute: NightOwlsRoute,
  PairsRoute: PairsRoute,
  PatchNotesRoute: PatchNotesRoute,
  QuietDaysRoute: QuietDaysRoute,
  QuotesRoute: QuotesRoute,
  ReplayRoute: ReplayRoute,
  RivalryRoute: RivalryRoute,
  SearchRoute: SearchRoute,
  SecretFinalRoute: SecretFinalRoute,
  ShipsRoute: ShipsRoute,
  SleepIndexRoute: SleepIndexRoute,
  SpotlightRoute: SpotlightRoute,
  StartersRoute: StartersRoute,
  StormRoute: StormRoute,
  UnhingedRoute: UnhingedRoute,
  VaultRoute: VaultRoute,
  VocabRoute: VocabRoute,
  VoiceMeterRoute: VoiceMeterRoute,
  WheelRoute: WheelRoute,
  WhoSaidItRoute: WhoSaidItRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
